create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id integer not null check (product_id > 0),
  quantity integer not null default 1 check (quantity between 1 and 99),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cart_items_user_product_unique unique (user_id, product_id)
);

create index if not exists cart_items_user_id_idx
  on public.cart_items (user_id);

alter table public.cart_items enable row level security;

drop policy if exists "Users can read their own cart" on public.cart_items;
create policy "Users can read their own cart"
  on public.cart_items for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can add to their own cart" on public.cart_items;
create policy "Users can add to their own cart"
  on public.cart_items for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own cart" on public.cart_items;
create policy "Users can update their own cart"
  on public.cart_items for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove from their own cart" on public.cart_items;
create policy "Users can remove from their own cart"
  on public.cart_items for delete to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.set_cart_items_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at
  before update on public.cart_items
  for each row execute function public.set_cart_items_updated_at();
